[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "`japanmap` is a package for Japanese map."
homepage = "https://github.com/SaitoTsutomu/japanmap"
include = ['japan.pkl', 'japan0.16.pkl', 'japan.png']
license = "Apache-2.0"
name = "japanmap"
readme = "README.rst"
version = "0.3.0"

[tool.poetry.dependencies]
opencv-python = "^4.7"
pillow = "^9.5"
python = "^3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.3"
flake8 = "^6.0"
isort = "^5.12"
jupyterlab = "^4.0"
matplotlib = "^3.7"
mypy = "^1.3"
pytest = "^7.3"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
