[tool.poetry]
name = "japanmap"
version = "0.0.22"
description = "`japanmap` is a package for Japanese map."
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
homepage = "https://github.com/SaitoTsutomu/japanmap"
classifiers = [
   "Development Status :: 1 - Planning",
   "License :: OSI Approved :: Python Software Foundation License",
   "Programming Language :: Python",
   "Topic :: Software Development",
   "Topic :: Scientific/Engineering",
]
license = "PSFL"
readme = "README.rst"
include = ['japan.pkl', 'japan0.16.pkl', 'japan.png']

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.2"
opencv-python = "^4.2.0"
Pillow = "^7.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
black = "^19.10b0"
isort = "^4.3.21"
mypy = "^0.770"
jupyter = "^1.0.0"
matplotlib = "^3.2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
