[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "`japanmap` is a package for Japanese map."
homepage = "https://github.com/SaitoTsutomu/japanmap"
include = ['japan.pkl', 'japan0.16.pkl', 'japan.png']
license = "MIT"
name = "japanmap"
readme = "README.rst"
version = "0.0.24"

[tool.poetry.dependencies]
python = "^3.8"
Pillow = "^8.1.0"
numpy = "^1.20.0"
opencv-python = "^4.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.7.0"
black = "^20.8b1"
mypy = "^0.800"
flake8 = "^3.8.4"
jupyter = "^1.0.0"
matplotlib = "^3.3.4"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
